apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app  # Matches the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
